import glob
import os
import sys
import shutil

# Returns a list of strings of the typed-repos generated by the script stored in "typed-repos"
def get_list_of_typed():
    content = None
    with open("../data/typed-repos-org") as f:
        content = f.readlines()
    content = [x.strip() for x in content]
    return content


def find_all_files(dir, name, new_folder):
    cwd = os.getcwd()
    cwd = cwd[:cwd.rindex("/")]
    cwd = cwd + f"/{new_folder}/{name}"
    shutil.copytree(dir, cwd)

def verify_args():
    args = sys.argv
    if len(args) == 3:
        if os.path.exists(args[1]) and os.path.exists(args[2]):
            return True
    return False

def main():
    if not verify_args():
        print("Usage: python3 ./copy-typed <all-repos> <new-folder>")
        sys.exit()

    # Retreives all of the metrics
    repo_names = get_list_of_typed()
    folder = sys.argv[1]
    new_folder = sys.argv[2]
    for subfolder in repo_names:
        find_all_files(folder + subfolder, subfolder, new_folder)

if __name__ == "__main__":
    main()