import glob
import os
import shutil

# Returns a list of strings of the typed-repos generated by the script stored in "typed-repos"
def get_list_of_typed():
    content = None
    with open("../data/typed-repos-org") as f:
        content = f.readlines()
    content = [x.strip() for x in content]
    return content


def find_all_files(dir, name):
    cwd = os.getcwd()
    cwd = cwd[:cwd.rindex("/")]
    cwd = cwd + f"/repos-stripped/{name}"
    shutil.copytree(dir, cwd)



def main():
    # Retreives all of the metrics
    repo_names = get_list_of_typed()
    folder = os.getcwd()
    folder = folder[:folder.rindex("/")]
    folder = folder + "/repos/"
    for subfolder in repo_names:
        find_all_files(folder + subfolder, subfolder)

if __name__ == "__main__":
    main()